all: start

start:
	sudo docker compose -f srcs/docker-compose.yml up -d
down:
	sudo docker compose -f srcs/docker-compose.yml down
build:
	sudo docker compose -f srcs/docker-compose.yml build
stop:
	sudo docker compose -f srcs/docker-compose.yml stop
